"""
Pydantic schemas for the Pricing Agent.
Defines inputs and outputs for validation.
"""

from pydantic import BaseModel, Field
from typing import Optional
from schemas.matching_schema import ProviderCandidate, IntentData


class PriceBreakdown(BaseModel):
    """Transparent calculation breakdown of the service quote."""
    base_fare: float = Field(..., description="Base rate from provider profile")
    distance_fare: float = Field(..., description="Calculated charge per kilometer traveled")
    urgency_surcharge: float = Field(..., description="Surcharge for urgent or same-day service")
    complexity_surcharge: float = Field(..., description="Multiplier-based fee for intermediate or complex work")
    materials_cost: float = Field(..., description="Estimated cost for required replacement parts/materials")
    surge_multiplier: float = Field(default=1.0, description="Dynamic surge conditions multiplier")
    loyalty_discount: float = Field(default=0.0, description="Loyalty discount subtracted from subtotal")
    total_price: float = Field(..., description="Sum total price of all breakdown elements")
    currency: str = Field(default="PKR", description="Currency code, defaulted to Pakistani Rupee")


class PricingInput(BaseModel):
    """Input payload for the Pricing Agent, containing provider details and user intent."""
    provider: ProviderCandidate = Field(..., description="The selected/matched provider candidate details")
    intent: IntentData = Field(..., description="The service request intent details")


class PricingOutput(BaseModel):
    """Output generated by the Pricing Agent containing calculations and customer-facing justification."""
    provider_name: str = Field(..., description="Name of the matched service provider")
    price_breakdown: PriceBreakdown = Field(..., description="Detailed fare itemization")
    price_range_min: float = Field(..., description="Lower limit of estimated price range")
    price_range_max: float = Field(..., description="Upper limit of estimated price range")
    explanation: str = Field(..., description="Polite, clear, multilingual customer-facing explanation of the cost breakdown")
    confidence: float = Field(default=1.0, ge=0.0, le=1.0, description="Confidence score of the pricing analysis")
